// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package org.genivi.vss;

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.Utils;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class GetEngineRpmQuery implements Query<GetEngineRpmQuery.Data, GetEngineRpmQuery.Data, Operation.Variables> {
  public static final String OPERATION_ID = "3aec5f6c2184821f3763b973f889d63f4b6f03191eee191d5986d3a1df0ed32d";

  public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
    "query GetEngineRpm {\n"
        + "  vehicle {\n"
        + "    __typename\n"
        + "    drivetrain {\n"
        + "      __typename\n"
        + "      internalCombustionEngine {\n"
        + "        __typename\n"
        + "        engine {\n"
        + "          __typename\n"
        + "          speed\n"
        + "        }\n"
        + "      }\n"
        + "    }\n"
        + "  }\n"
        + "}"
  );

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "GetEngineRpm";
    }
  };

  private final Operation.Variables variables;

  public GetEngineRpmQuery() {
    this.variables = Operation.EMPTY_VARIABLES;
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public GetEngineRpmQuery.Data wrapData(GetEngineRpmQuery.Data data) {
    return data;
  }

  @Override
  public Operation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<GetEngineRpmQuery.Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  @Override
  @NotNull
  public Response<GetEngineRpmQuery.Data> parse(@NotNull final BufferedSource source,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<GetEngineRpmQuery.Data> parse(@NotNull final ByteString byteString,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return parse(new Buffer().write(byteString), scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<GetEngineRpmQuery.Data> parse(@NotNull final BufferedSource source) throws
      IOException {
    return parse(source, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public Response<GetEngineRpmQuery.Data> parse(@NotNull final ByteString byteString) throws
      IOException {
    return parse(byteString, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
  }

  @NotNull
  @Override
  public ByteString composeRequestBody() {
    return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(final boolean autoPersistQueries,
      final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
  }

  public static final class Builder {
    Builder() {
    }

    public GetEngineRpmQuery build() {
      return new GetEngineRpmQuery();
    }
  }

  /**
   * Data from the response after executing this GraphQL operation
   */
  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("vehicle", "vehicle", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable Vehicle vehicle;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable Vehicle vehicle) {
      this.vehicle = vehicle;
    }

    public @Nullable Vehicle vehicle() {
      return this.vehicle;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], vehicle != null ? vehicle.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "vehicle=" + vehicle
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.vehicle == null) ? (that.vehicle == null) : this.vehicle.equals(that.vehicle));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (vehicle == null) ? 0 : vehicle.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Vehicle.Mapper vehicleFieldMapper = new Vehicle.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final Vehicle vehicle = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<Vehicle>() {
          @Override
          public Vehicle read(ResponseReader reader) {
            return vehicleFieldMapper.map(reader);
          }
        });
        return new Data(vehicle);
      }
    }
  }

  /**
   * Highlevel vehicle data.
   */
  public static class Vehicle {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("drivetrain", "drivetrain", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable Drivetrain drivetrain;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Vehicle(@NotNull String __typename, @Nullable Drivetrain drivetrain) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.drivetrain = drivetrain;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable Drivetrain drivetrain() {
      return this.drivetrain;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeObject($responseFields[1], drivetrain != null ? drivetrain.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Vehicle{"
          + "__typename=" + __typename + ", "
          + "drivetrain=" + drivetrain
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Vehicle) {
        Vehicle that = (Vehicle) o;
        return this.__typename.equals(that.__typename)
         && ((this.drivetrain == null) ? (that.drivetrain == null) : this.drivetrain.equals(that.drivetrain));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (drivetrain == null) ? 0 : drivetrain.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Vehicle> {
      final Drivetrain.Mapper drivetrainFieldMapper = new Drivetrain.Mapper();

      @Override
      public Vehicle map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Drivetrain drivetrain = reader.readObject($responseFields[1], new ResponseReader.ObjectReader<Drivetrain>() {
          @Override
          public Drivetrain read(ResponseReader reader) {
            return drivetrainFieldMapper.map(reader);
          }
        });
        return new Vehicle(__typename, drivetrain);
      }
    }
  }

  /**
   * Drivetrain data for internal combustion engines, transmissions, electric motors, etc.
   */
  public static class Drivetrain {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("internalCombustionEngine", "internalCombustionEngine", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable InternalCombustionEngine internalCombustionEngine;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Drivetrain(@NotNull String __typename,
        @Nullable InternalCombustionEngine internalCombustionEngine) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.internalCombustionEngine = internalCombustionEngine;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable InternalCombustionEngine internalCombustionEngine() {
      return this.internalCombustionEngine;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeObject($responseFields[1], internalCombustionEngine != null ? internalCombustionEngine.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Drivetrain{"
          + "__typename=" + __typename + ", "
          + "internalCombustionEngine=" + internalCombustionEngine
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Drivetrain) {
        Drivetrain that = (Drivetrain) o;
        return this.__typename.equals(that.__typename)
         && ((this.internalCombustionEngine == null) ? (that.internalCombustionEngine == null) : this.internalCombustionEngine.equals(that.internalCombustionEngine));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (internalCombustionEngine == null) ? 0 : internalCombustionEngine.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Drivetrain> {
      final InternalCombustionEngine.Mapper internalCombustionEngineFieldMapper = new InternalCombustionEngine.Mapper();

      @Override
      public Drivetrain map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final InternalCombustionEngine internalCombustionEngine = reader.readObject($responseFields[1], new ResponseReader.ObjectReader<InternalCombustionEngine>() {
          @Override
          public InternalCombustionEngine read(ResponseReader reader) {
            return internalCombustionEngineFieldMapper.map(reader);
          }
        });
        return new Drivetrain(__typename, internalCombustionEngine);
      }
    }
  }

  /**
   * Engine-specific data, stopping at the bell housing.
   */
  public static class InternalCombustionEngine {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("engine", "engine", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable Engine engine;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public InternalCombustionEngine(@NotNull String __typename, @Nullable Engine engine) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.engine = engine;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable Engine engine() {
      return this.engine;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeObject($responseFields[1], engine != null ? engine.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "InternalCombustionEngine{"
          + "__typename=" + __typename + ", "
          + "engine=" + engine
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof InternalCombustionEngine) {
        InternalCombustionEngine that = (InternalCombustionEngine) o;
        return this.__typename.equals(that.__typename)
         && ((this.engine == null) ? (that.engine == null) : this.engine.equals(that.engine));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (engine == null) ? 0 : engine.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<InternalCombustionEngine> {
      final Engine.Mapper engineFieldMapper = new Engine.Mapper();

      @Override
      public InternalCombustionEngine map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Engine engine = reader.readObject($responseFields[1], new ResponseReader.ObjectReader<Engine>() {
          @Override
          public Engine read(ResponseReader reader) {
            return engineFieldMapper.map(reader);
          }
        });
        return new InternalCombustionEngine(__typename, engine);
      }
    }
  }

  /**
   * Engine signals
   */
  public static class Engine {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("speed", "speed", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable Integer speed;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Engine(@NotNull String __typename, @Nullable Integer speed) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.speed = speed;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    /**
     * Engine speed measured as rotations per minute.
     */
    public @Nullable Integer speed() {
      return this.speed;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeInt($responseFields[1], speed);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Engine{"
          + "__typename=" + __typename + ", "
          + "speed=" + speed
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Engine) {
        Engine that = (Engine) o;
        return this.__typename.equals(that.__typename)
         && ((this.speed == null) ? (that.speed == null) : this.speed.equals(that.speed));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (speed == null) ? 0 : speed.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Engine> {
      @Override
      public Engine map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Integer speed = reader.readInt($responseFields[1]);
        return new Engine(__typename, speed);
      }
    }
  }
}
