// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package org.genivi.vss;

import com.apollographql.apollo.api.Operation;
import com.apollographql.apollo.api.OperationName;
import com.apollographql.apollo.api.Query;
import com.apollographql.apollo.api.Response;
import com.apollographql.apollo.api.ResponseField;
import com.apollographql.apollo.api.ScalarTypeAdapters;
import com.apollographql.apollo.api.internal.OperationRequestBodyComposer;
import com.apollographql.apollo.api.internal.QueryDocumentMinifier;
import com.apollographql.apollo.api.internal.ResponseFieldMapper;
import com.apollographql.apollo.api.internal.ResponseFieldMarshaller;
import com.apollographql.apollo.api.internal.ResponseReader;
import com.apollographql.apollo.api.internal.ResponseWriter;
import com.apollographql.apollo.api.internal.SimpleOperationResponseParser;
import com.apollographql.apollo.api.internal.Utils;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Collections;
import okio.Buffer;
import okio.BufferedSource;
import okio.ByteString;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class GetFuelDataQuery implements Query<GetFuelDataQuery.Data, GetFuelDataQuery.Data, Operation.Variables> {
  public static final String OPERATION_ID = "59d51f61637c13d41c221ecaf0a67b3c3dbb23273a1f9ebbb42fdb37d7a2dee6";

  public static final String QUERY_DOCUMENT = QueryDocumentMinifier.minify(
    "query GetFuelData {\n"
        + "  vehicle {\n"
        + "    __typename\n"
        + "    drivetrain {\n"
        + "      __typename\n"
        + "      fuelSystem {\n"
        + "        __typename\n"
        + "        level\n"
        + "        tankCapacity\n"
        + "      }\n"
        + "    }\n"
        + "  }\n"
        + "}"
  );

  public static final OperationName OPERATION_NAME = new OperationName() {
    @Override
    public String name() {
      return "GetFuelData";
    }
  };

  private final Operation.Variables variables;

  public GetFuelDataQuery() {
    this.variables = Operation.EMPTY_VARIABLES;
  }

  @Override
  public String operationId() {
    return OPERATION_ID;
  }

  @Override
  public String queryDocument() {
    return QUERY_DOCUMENT;
  }

  @Override
  public GetFuelDataQuery.Data wrapData(GetFuelDataQuery.Data data) {
    return data;
  }

  @Override
  public Operation.Variables variables() {
    return variables;
  }

  @Override
  public ResponseFieldMapper<GetFuelDataQuery.Data> responseFieldMapper() {
    return new Data.Mapper();
  }

  public static Builder builder() {
    return new Builder();
  }

  @Override
  public OperationName name() {
    return OPERATION_NAME;
  }

  @Override
  @NotNull
  public Response<GetFuelDataQuery.Data> parse(@NotNull final BufferedSource source,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return SimpleOperationResponseParser.parse(source, this, scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<GetFuelDataQuery.Data> parse(@NotNull final ByteString byteString,
      @NotNull final ScalarTypeAdapters scalarTypeAdapters) throws IOException {
    return parse(new Buffer().write(byteString), scalarTypeAdapters);
  }

  @Override
  @NotNull
  public Response<GetFuelDataQuery.Data> parse(@NotNull final BufferedSource source) throws
      IOException {
    return parse(source, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public Response<GetFuelDataQuery.Data> parse(@NotNull final ByteString byteString) throws
      IOException {
    return parse(byteString, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(@NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, false, true, scalarTypeAdapters);
  }

  @NotNull
  @Override
  public ByteString composeRequestBody() {
    return OperationRequestBodyComposer.compose(this, false, true, ScalarTypeAdapters.DEFAULT);
  }

  @Override
  @NotNull
  public ByteString composeRequestBody(final boolean autoPersistQueries,
      final boolean withQueryDocument, @NotNull final ScalarTypeAdapters scalarTypeAdapters) {
    return OperationRequestBodyComposer.compose(this, autoPersistQueries, withQueryDocument, scalarTypeAdapters);
  }

  public static final class Builder {
    Builder() {
    }

    public GetFuelDataQuery build() {
      return new GetFuelDataQuery();
    }
  }

  /**
   * Data from the response after executing this GraphQL operation
   */
  public static class Data implements Operation.Data {
    static final ResponseField[] $responseFields = {
      ResponseField.forObject("vehicle", "vehicle", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @Nullable Vehicle vehicle;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Data(@Nullable Vehicle vehicle) {
      this.vehicle = vehicle;
    }

    public @Nullable Vehicle vehicle() {
      return this.vehicle;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeObject($responseFields[0], vehicle != null ? vehicle.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Data{"
          + "vehicle=" + vehicle
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Data) {
        Data that = (Data) o;
        return ((this.vehicle == null) ? (that.vehicle == null) : this.vehicle.equals(that.vehicle));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= (vehicle == null) ? 0 : vehicle.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Data> {
      final Vehicle.Mapper vehicleFieldMapper = new Vehicle.Mapper();

      @Override
      public Data map(ResponseReader reader) {
        final Vehicle vehicle = reader.readObject($responseFields[0], new ResponseReader.ObjectReader<Vehicle>() {
          @Override
          public Vehicle read(ResponseReader reader) {
            return vehicleFieldMapper.map(reader);
          }
        });
        return new Data(vehicle);
      }
    }
  }

  /**
   * Highlevel vehicle data.
   */
  public static class Vehicle {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("drivetrain", "drivetrain", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable Drivetrain drivetrain;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Vehicle(@NotNull String __typename, @Nullable Drivetrain drivetrain) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.drivetrain = drivetrain;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable Drivetrain drivetrain() {
      return this.drivetrain;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeObject($responseFields[1], drivetrain != null ? drivetrain.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Vehicle{"
          + "__typename=" + __typename + ", "
          + "drivetrain=" + drivetrain
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Vehicle) {
        Vehicle that = (Vehicle) o;
        return this.__typename.equals(that.__typename)
         && ((this.drivetrain == null) ? (that.drivetrain == null) : this.drivetrain.equals(that.drivetrain));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (drivetrain == null) ? 0 : drivetrain.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Vehicle> {
      final Drivetrain.Mapper drivetrainFieldMapper = new Drivetrain.Mapper();

      @Override
      public Vehicle map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Drivetrain drivetrain = reader.readObject($responseFields[1], new ResponseReader.ObjectReader<Drivetrain>() {
          @Override
          public Drivetrain read(ResponseReader reader) {
            return drivetrainFieldMapper.map(reader);
          }
        });
        return new Vehicle(__typename, drivetrain);
      }
    }
  }

  /**
   * Drivetrain data for internal combustion engines, transmissions, electric motors, etc.
   */
  public static class Drivetrain {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forObject("fuelSystem", "fuelSystem", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable FuelSystem fuelSystem;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public Drivetrain(@NotNull String __typename, @Nullable FuelSystem fuelSystem) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.fuelSystem = fuelSystem;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    public @Nullable FuelSystem fuelSystem() {
      return this.fuelSystem;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeObject($responseFields[1], fuelSystem != null ? fuelSystem.marshaller() : null);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "Drivetrain{"
          + "__typename=" + __typename + ", "
          + "fuelSystem=" + fuelSystem
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof Drivetrain) {
        Drivetrain that = (Drivetrain) o;
        return this.__typename.equals(that.__typename)
         && ((this.fuelSystem == null) ? (that.fuelSystem == null) : this.fuelSystem.equals(that.fuelSystem));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (fuelSystem == null) ? 0 : fuelSystem.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<Drivetrain> {
      final FuelSystem.Mapper fuelSystemFieldMapper = new FuelSystem.Mapper();

      @Override
      public Drivetrain map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final FuelSystem fuelSystem = reader.readObject($responseFields[1], new ResponseReader.ObjectReader<FuelSystem>() {
          @Override
          public FuelSystem read(ResponseReader reader) {
            return fuelSystemFieldMapper.map(reader);
          }
        });
        return new Drivetrain(__typename, fuelSystem);
      }
    }
  }

  /**
   * Fuel system data.
   */
  public static class FuelSystem {
    static final ResponseField[] $responseFields = {
      ResponseField.forString("__typename", "__typename", null, false, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("level", "level", null, true, Collections.<ResponseField.Condition>emptyList()),
      ResponseField.forInt("tankCapacity", "tankCapacity", null, true, Collections.<ResponseField.Condition>emptyList())
    };

    final @NotNull String __typename;

    final @Nullable Integer level;

    final @Nullable Integer tankCapacity;

    private transient volatile String $toString;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    public FuelSystem(@NotNull String __typename, @Nullable Integer level,
        @Nullable Integer tankCapacity) {
      this.__typename = Utils.checkNotNull(__typename, "__typename == null");
      this.level = level;
      this.tankCapacity = tankCapacity;
    }

    public @NotNull String __typename() {
      return this.__typename;
    }

    /**
     * Level in fuel tank as percent of capacity. 0 = empty. 100 = full.
     */
    public @Nullable Integer level() {
      return this.level;
    }

    /**
     * Capacity of the fuel tank in liters
     */
    public @Nullable Integer tankCapacity() {
      return this.tankCapacity;
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeString($responseFields[0], __typename);
          writer.writeInt($responseFields[1], level);
          writer.writeInt($responseFields[2], tankCapacity);
        }
      };
    }

    @Override
    public String toString() {
      if ($toString == null) {
        $toString = "FuelSystem{"
          + "__typename=" + __typename + ", "
          + "level=" + level + ", "
          + "tankCapacity=" + tankCapacity
          + "}";
      }
      return $toString;
    }

    @Override
    public boolean equals(Object o) {
      if (o == this) {
        return true;
      }
      if (o instanceof FuelSystem) {
        FuelSystem that = (FuelSystem) o;
        return this.__typename.equals(that.__typename)
         && ((this.level == null) ? (that.level == null) : this.level.equals(that.level))
         && ((this.tankCapacity == null) ? (that.tankCapacity == null) : this.tankCapacity.equals(that.tankCapacity));
      }
      return false;
    }

    @Override
    public int hashCode() {
      if (!$hashCodeMemoized) {
        int h = 1;
        h *= 1000003;
        h ^= __typename.hashCode();
        h *= 1000003;
        h ^= (level == null) ? 0 : level.hashCode();
        h *= 1000003;
        h ^= (tankCapacity == null) ? 0 : tankCapacity.hashCode();
        $hashCode = h;
        $hashCodeMemoized = true;
      }
      return $hashCode;
    }

    public static final class Mapper implements ResponseFieldMapper<FuelSystem> {
      @Override
      public FuelSystem map(ResponseReader reader) {
        final String __typename = reader.readString($responseFields[0]);
        final Integer level = reader.readInt($responseFields[1]);
        final Integer tankCapacity = reader.readInt($responseFields[2]);
        return new FuelSystem(__typename, level, tankCapacity);
      }
    }
  }
}
